version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # Puerto para la comunicación con RabbitMQ
      - "15672:15672"  # Puerto para el panel de control de RabbitMQ (interfaz de gestión)
    environment:
      RABBITMQ_DEFAULT_USER: user  # Nombre de usuario para acceder a la interfaz de gestión
      RABBITMQ_DEFAULT_PASS: password  # Contraseña para acceder a la interfaz de gestión

